/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-08 13:59:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.UserModel;
import user.UserDBUtil;
import java.util.*;

public final class updateUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("user.UserDBUtil");
    _jspx_imports_classes.add("user.UserModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Update User</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>Update User</h2>\r\n");
      out.write("    \r\n");
      out.write("    ");

                String userIdStr = request.getParameter("id"); // Retrieve the user ID from the request parameter
                if (userIdStr != null) {
                    try {
                        int userId = Integer.parseInt(userIdStr); // Parse the user ID to an integer
                        UserModel user = UserDBUtil.getUserDetailsById(String.valueOf(userId)); // Get user details by ID
                        if (user != null) { // If the user is found, populate the form
        
      out.write("\r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/update\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( user.getUserId() );
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"firstName\">First Name:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"firstName\" name=\"firstName\" value=\"");
      out.print( user.getFirstName() );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"lastName\" name=\"lastName\" value=\"");
      out.print( user.getLastName() );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"licenseNo\">License No:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"licenseNo\" name=\"licenseNo\" value=\"");
      out.print( user.getLicenseNo() );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"licenseExpiryDate\">License Expiry Date:</label>\r\n");
      out.write("                        <input type=\"date\" id=\"licenseExpiryDate\" name=\"licenseExpiryDate\" value=\"");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd").format(user.getLicenseExpiryDate()) );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"email\">Email:</label>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( user.getEmail() );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"contactNo\">Contact No:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"contactNo\" name=\"contactNo\" value=\"");
      out.print( user.getContactNo() );
      out.write("\" required/><br>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\">Update</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                ");

                } else {
                
      out.write("\r\n");
      out.write("                    <p>User not found.</p>\r\n");
      out.write("                ");

                }
            } catch (NumberFormatException e) {
        
      out.write("\r\n");
      out.write("            <p>Invalid user ID format.</p>\r\n");
      out.write("        ");

            }
        } else {
    
      out.write("\r\n");
      out.write("        <p>Invalid user ID.</p>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
