/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-10 07:06:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Online Car Rental</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap 5 CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome 6 -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        html, body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .hero {\r\n");
      out.write("            background: url('images/33.jpg') no-repeat center center/cover;\r\n");
      out.write("            min-height: 80vh;\r\n");
      out.write("            color: white;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-overlay {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.6);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 3rem 1rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: white !important;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ff6b6b !important;\r\n");
      out.write("        }\r\n");
      out.write("        .login-btn {\r\n");
      out.write("            background-color: #ff2d75;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .login-btn:hover {\r\n");
      out.write("            background-color: #e01b5c;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .section-heading {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .section-heading:after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: #ff2d75;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"bg-dark text-white py-2\">\r\n");
      out.write("    <div class=\"container d-flex flex-wrap justify-content-between align-items-center\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"images/Rental Car Logo - Made with PosterMyWall.jpg\" alt=\"Logo\" height=\"35\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d-none d-md-flex gap-4\">\r\n");
      out.write("            <span><i class=\"fa fa-envelope me-2\"></i>carsones@gmail.com</span>\r\n");
      out.write("            <span><i class=\"fa fa-phone me-2\"></i> +94 77 89 89 899</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("            <a href=\"#\" class=\"text-white\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white\"><i class=\"fab fa-google-plus-g\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"btn login-btn btn-sm\">Register</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-black\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand d-lg-none\" href=\"vehicle/all\">Vehicle Rental</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navMenu\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-center\" id=\"navMenu\">\r\n");
      out.write("            <ul class=\"navbar-nav gap-4\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"vehicle/all\">Vehicle Dashboard</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"reservation\">Reservations</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About Us</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">FAQs</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact Us</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<div class=\"hero\">\r\n");
      out.write("    <div class=\"hero-overlay\">\r\n");
      out.write("        <div class=\"hero-content\">\r\n");
      out.write("            <h1 class=\"display-5 fw-bold\">FIND THE RIGHT VEHICLE FOR YOU</h1>\r\n");
      out.write("            <p class=\"lead\">We have more than a thousand vehicles for you to choose from.</p>\r\n");
      out.write("            <div class=\"mt-4\">\r\n");
      out.write("                <a href=\"vehicle/all\" class=\"btn btn-danger btn-lg px-4\">Explore Vehicles <i class=\"fa fa-arrow-right ms-2\"></i></a>\r\n");
      out.write("                <a href=\"reservation\" class=\"btn btn-outline-light btn-lg px-4 ms-2\">My Reservations <i class=\"fa fa-calendar-check ms-2\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Features Section -->\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <h2 class=\"section-heading\">Why Choose Our Service?</h2>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card h-100 feature-card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body text-center\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <i class=\"fas fa-car-side text-primary\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h4 class=\"card-title\">Wide Selection</h4>\r\n");
      out.write("                    <p class=\"card-text\">Choose from our extensive fleet of vehicles to match your specific needs and preferences.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card h-100 feature-card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body text-center\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <i class=\"fas fa-hand-holding-usd text-success\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h4 class=\"card-title\">Best Rates</h4>\r\n");
      out.write("                    <p class=\"card-text\">We offer competitive pricing with no hidden fees. Get the best value for your money.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card h-100 feature-card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body text-center\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <i class=\"fas fa-headset text-danger\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h4 class=\"card-title\">24/7 Support</h4>\r\n");
      out.write("                    <p class=\"card-text\">Our customer service team is available around the clock to assist with any questions or issues.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Call to Action -->\r\n");
      out.write("<div class=\"bg-dark text-white py-5 text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Ready to book your next vehicle?</h2>\r\n");
      out.write("        <p class=\"lead\">Join thousands of satisfied customers who trust us for their transportation needs.</p>\r\n");
      out.write("        <a href=\"reservation/insert\" class=\"btn btn-danger btn-lg mt-3\">Make a Reservation Now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-black text-white py-4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>About Us</h5>\r\n");
      out.write("                <p>We are a premier car rental service dedicated to providing quality vehicles and excellent service to our customers.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>Quick Links</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><a href=\"vehicle/all\" class=\"text-white\">Vehicles</a></li>\r\n");
      out.write("                    <li><a href=\"reservation\" class=\"text-white\">Reservations</a></li>\r\n");
      out.write("                    <li><a href=\"#\" class=\"text-white\">Terms & Conditions</a></li>\r\n");
      out.write("                    <li><a href=\"#\" class=\"text-white\">Privacy Policy</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>Contact Us</h5>\r\n");
      out.write("                <address>\r\n");
      out.write("                    <i class=\"fas fa-map-marker-alt me-2\"></i> 123 Main Street, Colombo<br>\r\n");
      out.write("                    <i class=\"fas fa-phone me-2\"></i> +94 77 89 89 899<br>\r\n");
      out.write("                    <i class=\"fas fa-envelope me-2\"></i> carsones@gmail.com\r\n");
      out.write("                </address>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mt-4\">\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("            <p class=\"mb-0\">&copy; 2023 GoGo Car Rental. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
