/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-10 06:49:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import vehicle.Vehicle;

public final class vehicleAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1746857639327L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vehicle.Vehicle");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Available Vehicles</title>\r\n");
      out.write("    <!-- Bootstrap 5 CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .vehicle-card {\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .vehicle-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-img-top {\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .daily-rate {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #dc3545;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .section-heading {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .section-heading:after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-book-now {\r\n");
      out.write("            background-color: #dc3545;\r\n");
      out.write("            border-color: #dc3545;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-book-now:hover {\r\n");
      out.write("            background-color: #c82333;\r\n");
      out.write("            border-color: #bd2130;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .vehicle-features {\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-icon {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("            color: #6c757d;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark mb-4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/home\">\r\n");
      out.write("            <strong>CARSONES</strong> Rental\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.print( request.getServletPath().contains("reservation") ? "active" : "" );
      out.write("\" \r\n");
      out.write("                       href=\"");
      out.print( request.getContextPath() );
      out.write("/reservation\">Reservations</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.print( request.getServletPath().contains("user") ? "active" : "" );
      out.write("\" \r\n");
      out.write("                       href=\"");
      out.print( request.getContextPath() );
      out.write("/user\">Users</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.print( request.getServletPath().contains("vehicle") ? "active" : "" );
      out.write("\" \r\n");
      out.write("                       href=\"");
      out.print( request.getContextPath() );
      out.write("/vehicle\">Vehicles</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.print( request.getServletPath().contains("location") ? "active" : "" );
      out.write("\" \r\n");
      out.write("                       href=\"");
      out.print( request.getContextPath() );
      out.write("/location\">Locations</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"d-flex\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/insert\" class=\"btn btn-outline-light btn-sm\">Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <h2 class=\"section-heading\">Available Vehicles</h2>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        ");

            List<Vehicle> vehicles = (List<Vehicle>)request.getAttribute("vehicles");
            if (vehicles != null && !vehicles.isEmpty()) {
                for (Vehicle v : vehicles) {
        
      out.write("\r\n");
      out.write("        <div class=\"col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card vehicle-card shadow-sm\">\r\n");
      out.write("                <img src=\"../images/Rent_car.png\" class=\"card-img-top\" alt=\"Vehicle Image\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title fw-bold\">");
      out.print( v.getBrand() );
      out.write(' ');
      out.print( v.getModel() );
      out.write("</h5>\r\n");
      out.write("                    <div class=\"vehicle-features\">\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-car feature-icon\"></i> <strong>Category:</strong> ");
      out.print( v.getCategory() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-cog feature-icon\"></i> <strong>Gear:</strong> ");
      out.print( v.getGear() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-palette feature-icon\"></i> <strong>Color:</strong> ");
      out.print( v.getColor() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-users feature-icon\"></i> <strong>Seats:</strong> ");
      out.print( v.getSeat_no() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-gas-pump feature-icon\"></i> <strong>Fuel:</strong> ");
      out.print( v.getFuel_option() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"mb-2\"><i class=\"fas fa-id-card feature-icon\"></i> <strong>Plate No:</strong> ");
      out.print( v.getPlate_no() );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"daily-rate mt-3\">Rs. ");
      out.print( v.getDaily_rate() );
      out.write(" / day</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer bg-white border-0 pb-3 text-center\">\r\n");
      out.write("                    <a href=\"../reservation/insert?vehicleId=");
      out.print( v.getVehicle_id() );
      out.write("\" class=\"btn btn-book-now btn-lg w-100\">\r\n");
      out.write("                        <i class=\"fas fa-calendar-check me-2\"></i>Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 
                }
            } else {
        
      out.write("\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <div class=\"alert alert-info text-center\">\r\n");
      out.write("                    <i class=\"fas fa-info-circle me-2\"></i> No vehicles available at the moment.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Call to Action Section -->\r\n");
      out.write("<div class=\"bg-dark text-white py-5 text-center mt-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Need Help Choosing a Vehicle?</h2>\r\n");
      out.write("        <p class=\"lead\">Our team is ready to assist you with finding the perfect vehicle for your needs.</p>\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-outline-light btn-lg mt-3\">Contact Us</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-black text-white py-4 mt-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>About Us</h5>\r\n");
      out.write("                <p>We are a premier car rental service dedicated to providing quality vehicles and excellent service to our customers.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>Quick Links</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><a href=\"/GoGo/vehicle/all\" class=\"text-white\">Vehicles</a></li>\r\n");
      out.write("                    <li><a href=\"/GoGo/reservation\" class=\"text-white\">Reservations</a></li>\r\n");
      out.write("                    <li><a href=\"#\" class=\"text-white\">Terms & Conditions</a></li>\r\n");
      out.write("                    <li><a href=\"#\" class=\"text-white\">Privacy Policy</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5>Contact Us</h5>\r\n");
      out.write("                <address>\r\n");
      out.write("                    <i class=\"fas fa-map-marker-alt me-2\"></i> 123 Main Street, Colombo<br>\r\n");
      out.write("                    <i class=\"fas fa-phone me-2\"></i> +94 77 89 89 899<br>\r\n");
      out.write("                    <i class=\"fas fa-envelope me-2\"></i> carsones@gmail.com\r\n");
      out.write("                </address>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mt-4\">\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("            <p class=\"mb-0\">&copy; 2023 GoGo Car Rental. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
